---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.user }}-rhsso-ca-secret
  namespace: {{ .Values.user }}-prod-istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.user }}-rhsso-ca-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.user }}-rhsso-ca-secret
  namespace: {{ .Values.user }}-prod-istio-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rhsso-ca-secret
  namespace: {{ .Values.user }}-prod-istio-system
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ .Values.user }}-rhsso-ca-secret
      restartPolicy: Never
      containers:
      - name: maven
        image: quay.io/openshift/origin-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          set -euxo pipefail
          oc extract secret/router-ca -n openshift-ingress-operator --confirm --to=/tmp/{{ .Values.user }}
          oc -n {{ .Values.user }}-prod-istio-system create secret generic openshift-wildcard --from-file=extra.pem=/tmp/{{ .Values.user }}/tls.crt
          oc -n {{ .Values.user }}-prod-istio-system get secret openshift-wildcard
