#oc apply -f mesh-admin.yaml
#oc adm policy add-cluster-role-to-user servicemesh-admin <username>
#oc adm policy add-role-to-user admin <username> -n <mesh_control_plane> (E.g. istio-system)
#oc adm policy add-role-to-user servicemesh-admin-pods <username> -n openshift-operators
#oc adm policy add-role-to-user servicemesh-admin-pods <username> -n <mesh_data_plane_app_X>
#oc adm policy add-role-to-user servicemesh-admin-pods <username> -n <mesh_data_plane_app_Y>
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemesh-admin
rules:
- apiGroups:
  - maistra.io
  resources:
  - servicemeshcontrolplanes
  - servicemeshmemberrolls
  - servicemeshmembers
  - servicemeshextensions
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - catalogsources
  - installplans
  - subscriptions
  verbs:
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - catalogsources
  - installplans
  - subscriptions
  - operatorgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  - packagemanifests/icon
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  - authentication.maistra.io
  - rbac.maistra.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - projects
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemesh-admin-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/exec
  - secrets
  - configmap
  - routes
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  - secrets
  - configmaps
  - routes
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
    - route.openshift.io
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - ""
    - apps
  resources:
    - deployments/scale
  verbs:
    - '*'
