---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: control-gateway
  namespace: {{ .Values.user }}-dev-istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  servers:
    - hosts:
        - istio-ingressgateway-{{ .Values.user }}-dev-istio-system.{{ .Values.domain }}
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway
