---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.user }}-dev-basic
  namespace: {{ .Values.user }}-dev-istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      logAsJSON: true
  profiles:
    - default
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.3
  telemetry:
    type: Istiod
