= Pre-Lab Preparation Setup
:toc:

This describes the setup required in a cluster in order to host `X` number of concurrent users working on the link:../README.adoc[`Heading to Production with RH OSSM`] labs.

== Setup Commands Summary

----
export CLUSTER_API=https://api.cluster-klvh8.klvh8.sandbox1886.opentlc.com:6443
export LAB_PARTICIPANTS=5
export OCP_DOMAIN=apps.cluster-klvh8.klvh8.sandbox1886.opentlc.com
export CLUSTERNAME=cluster-klvh8.klvh8.sandbox1886
export BASEDOMAIN=opentlc.com
export CLUSTER_ADMIN=
export CLUSTER_ADMIN_PASS=
----

* *Scenario-1:*  `./run-setup-scenario-1.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $LAB_PARTICIPANTS htpasswd-secret`
* *Scenario-3:*  `./run-setup-scenario-2.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $LAB_PARTICIPANTS htpasswd-secret`
* *Scenario-3b:* `./run-setup-scenario-3.sh $OCP_DOMAIN $LAB_PARTICIPANTS
* *Scenario-4:*  `./run-setup-scenario-4.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN $LAB_PARTICIPANTS`
* *Scenario-4b-once-per-participant:* SEE BELOW (to be done once per participant)
* *Scenario-6:*  `./run-setup-scenario-6.sh premium-broker partner-istio-system $OCP_DOMAIN partner`

== Setup Scenario-1

The script will

* Setup OSSM required operators, create all the DEV namespaces, `SMCP`/`SMM` resources, mesh roles and create the users based on the number of participants defined
** Parameters
1. cluster admin username
2. cluster admin password
3. OCP cluster API URL
4. No. of lab participants
5. OCP `httpaswd` secret name (`oc get secret  -n openshift-config |grep htpasswd`)
** Script
+
----
./run-setup-scenario-1.sh opentlc-mgr r3dh4t1! https://api.cluster-w4h2j.w4h2j.sandbox2385.opentlc.com:6443/ 5 htpasswd-secret
----

=== Reset Scenario-1

The script will reset the whole of the setup for Scenario-1

* Script Parameters
1. cluster admin username
2. cluster admin password
3. OCP cluster API URL
4. No. of lab participants
5. OCP `httpaswd` secret name (`oc get secret  -n openshift-config |grep htpasswd`)
----
./reset-setup-scenario-1.sh <cluster-admin> <cluster-admin-password> https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ 5 htpasswd-secret
----

== Setup Scenario-3

The script will do the setup for Scenario-3 including creation of PROD Users & their rolebindings, the PROD CP Namespace and all Prod Mesh member namespaces.

* Script Parameters
1. cluster admin username
2. cluster admin password
3. OCP cluster API URL
4. No. of lab participants
5. OCP `httpaswd` secret name (`oc get secret  -n openshift-config |grep htpasswd`)
----
./run-setup-scenario-2.sh <cluster-admin> <cluster-admin-password> https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ 5 htpasswd-secret
----

=== Reset Scenario-3

The script will reset the whole of the setup for Scenario-3

[WARNING]
====
TODO
====

== Setup Scenario-4

=== Step 1: Setup `RHSSO` and Keycloak resources.

First setup RHSSO namespace, RHSSO operator, KeycloakRealm resource, KeycloakClient (1 per participant) resource, KeycloakUser

* The script will perform the setup for Scenario-4
1. cluster admin username
2. cluster admin password
3. OCP cluster API URL
4. Cluster Name (eg. cluster-f4fbs.f4fbs.sandbox354)
5. Cluster Domain (eg. opentlc.com)
6. No. of lab participants

----
./run-setup-scenario-4.sh <cluster-admin> <cluster-admin-password> https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 5
----

=== Step 2: Add RHSSO TLS certs to `Istiod`

The second step will extract and create a secret from the OCP Ingress certs in each `*user-x*-prod-istio-system` namespace and mount via a volume into each _IstioD_ to be used when sending a validation of the `JWT` request to RHSSO.

[NOTE]
====
This needs to be done ONCE for each participant at the end of Lab-3

- ./run-setup-scenario-4b-after-LAB-3.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 1
- ./run-setup-scenario-4b-after-LAB-3.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 2
- ./run-setup-scenario-4b-after-LAB-3.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 3
- ./run-setup-scenario-4b-after-LAB-3.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 4
- ./run-setup-scenario-4b-after-LAB-3.sh $CLUSTER_ADMIN $CLUSTER_ADMIN_PASS https://api.$CLUSTERNAME.$BASEDOMAIN:6443/ $CLUSTERNAME $BASEDOMAIN 5
====

